# Generated by Django 5.2.4 on 2025-07-15 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='物品标题')),
                ('description', models.TextField(blank=True, null=True, verbose_name='详细描述')),
                ('type', models.CharField(choices=[('LOST', '失物'), ('FOUND', '拾物')], max_length=10, verbose_name='信息类型')),
                ('item_class', models.CharField(choices=[('电子产品', '电子产品'), ('证件卡片', '证件卡片'), ('学习用品', '学习用品'), ('生活用品', '生活用品'), ('其他', '其他')], default='其他', max_length=20, verbose_name='物品类别')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='地点描述')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='纬度')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='经度')),
                ('contact', models.EmailField(max_length=254, verbose_name='联系邮箱')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='是否已处理')),
                ('time', models.DateField(blank=True, null=True, verbose_name='事件日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('image', models.ImageField(blank=True, null=True, upload_to='item_images/', verbose_name='物品图片')),
            ],
        ),
    ]
